# Generated by Django 2.1.1 on 2018-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20181118_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_goods',
            name='size',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l')], max_length=10),
        ),
    ]
